Add key.ignore.id.strategy to provide different options for Document ID generation
aiven/opensearch-connector-for-apache-kafka pull request #139
Opened 2022-11-09 08:46 UTC by deepdatta

With the current `key.ignore` config  we can choose between OpenSearch Document ID generated based on the record's "key" or "topic+partition+offset". 
For our particular use case, we needed an option to not have any Document ID published from the Connector, instead one will be auto generated in OpenSearch.
Adding the `key.ignore.id.strategy` strategy config to provide multiple Document ID generation option when `key.ignore` = true.
Available strategies {none : No Doc ID is added, record.key : Generated from the record's key, topic.partition.offset : Generated as record's ``topic+partition+offset``}

2022-11-09 14:55 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/OpensearchSinkConnectorConfig.java
> +                    + "Note that this is a global config that applies to all topics, use "
I think we need to change the documentation here, basically we are splitting the setting into two: the intent (ignore record key) and the generation (how to generate the key). 

```
"Whether to ignore the record key for the purpose of forming the Opensearch document ID."
 + " When this is set to ``true``, document IDs will be generated according to the ``" 
 + KEY_IGNORE_ID_STRATEGY_CONFIG + "`` strategy.\n" 
 + "Note that this is a global config that applies to all topics, use ``"
 + TOPIC_KEY_IGNORE_CONFIG + "`` to apply `" + KEY_IGNORE_ID_STRATEGY_CONFIG 
 + "` strategy for specific topics only.";
```

May be something along these lines. The default `KEY_IGNORE_ID_STRATEGY_CONFIG` should be ``topic+partition+offset``.

2022-11-09 14:57 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/OpensearchSinkConnectorConfig.java
> +            "Specifies the strategy to generate the Document ID. Only applicable when ``" + KEY_IGNORE_CONFIG + "`` is"
```
 "Specifies the strategy to generate the Document ID. Only applicable when ``" + KEY_IGNORE_CONFIG + "`` is"
                    + " ``true`` or specific topics are configured using``" + TOPIC_KEY_IGNORE_CONFIG + "``. Available strategies " + RecordConverter.DocumentIDStrategy.describe() + ", if not specified, the default strategy is ``topic+partition+offset``.\n";
```

2022-11-09 14:58 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/OpensearchSinkConnectorConfig.java
> +                    + "Note that this is a global config that applies to all topics.";
`Note that this is a global config that applies to all topic` - this is not strictly correct, it depends where KEY_IGNORE_DOC is set or TOPIC_KEY_IGNORE_CONFIG is set.

2022-11-10 14:43 UTC, reta commented on .github/workflows/main_and_pr_workflow.yml
> +  check:
@deepdatta you probably need to rebase

2022-11-16 19:55 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/OpensearchSinkConnectorConfig.java
> +    public RecordConverter.DocumentIDStrategy globalDocIdStrategy() {
I believe we don't need both methods, it is confusing which one does what, having just one should be sufficient:
```
public RecordConverter.DocumentIDStrategy docIdStrategy(String topic) {
    return `ignoreKey() ||  topicIgnoreKey().contains(topic)` ? RecordConverter.DocumentIDStrategy.fromString(getString(KEY_IGNORE_ID_STRATEGY_CONFIG) : RecordConverter.DocumentIDStrategy.RECORD_KEY;
}
```

2022-11-16 19:57 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/OpensearchSinkConnectorConfig.java
> +    public RecordConverter.DocumentIDStrategy globalDocIdStrategy() {
(to mitigate possible impact on re-checking configuration every time, we could may be cache it inside `RecordConverter`)

2022-11-16 19:58 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/RecordConverter.java
> +        final DocumentIDStrategy docIdStrategy = getDocIdStrategy(record);
`final DocumentIDStrategy docIdStrategy = config.docIdStrategy(record.topic());`

2022-11-16 20:00 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/RecordConverter.java
> +    public enum DocumentIDStrategy {
Could you make this enum top level please?  (since it belongs to configuration as well)

2022-11-17 15:18 UTC, C0urante commented on src/main/java/io/aiven/kafka/connect/opensearch/OpensearchSinkConnectorConfig.java
> +                    + "If not specified, the default generation strategy is ``topic+partition+offset``.\n";
Should this be `topic.partition.offset`?

2022-11-18 13:29 UTC, reta commented on docs/opensearch-sink-connector-config-options.rst
> +Opensearch Sink Connector Configuration Options
Please change back to `OpenSearch`, we are constantly being "beaten" by that (see please https://github.com/opensearch-project/OpenSearch/blob/main/README.md)

2022-11-18 13:33 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/DocumentIDStrategy.java
> +    public static String[] names() {
Please make it `private static`, or even remove it, this method is used only in one place https://github.com/aiven/opensearch-connector-for-apache-kafka/pull/139/files#diff-f57f55041b60deaa26a11d81710270e886995c941beaaeaa604aa7f205b83fc1R135

2022-11-18 13:33 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/DocumentIDStrategy.java
> +    public static String describe() {
Where this is used?

2022-11-18 13:35 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/DocumentIDStrategy.java
> +    public Boolean nameEquals(final String name) {
Please remove, not needed: `name().equalsIgnoreCase(name)`

2022-11-18 13:35 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/DocumentIDStrategy.java
> +            if (strategy.nameEquals(name)) {
`strategy.name().equalsIgnoreCase(name)`

2022-11-18 13:42 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/RecordConverter.java
> +        globalDocIdGenerator = (config != null && config.ignoreKey()) ? config.docIdStrategy()
https://github.com/aiven/opensearch-connector-for-apache-kafka/pull/139#discussion_r1024447961 , the `RecordConverter` should not make the decision what docId strategy to use - it has to be provided by configuration

2022-11-18 13:45 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/RecordConverter.java
> +    public static String convertKey(final Schema keySchema, final Object key) {
It is used only by `DocumentIDStrategy`, so it makes sense to move it there (and make it `private static`)

2022-11-18 13:51 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/DocumentIDStrategy.java
> +    public DocWriteRequest<?> updateIndexRequest(final IndexRequest request,
Please just `updateRequest`, overloaded methods for  `IndexRequest` and `DeleteRequest`

2022-11-18 13:52 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/DocumentIDStrategy.java
> +    public DocWriteRequest<?> updateDeleteRequest(final DeleteRequest request,
Please just `updateRequest`

2022-11-18 13:52 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/RecordConverter.java
> +        final DocumentIDStrategy docIdStrategy = getDocIdStrategy(record.topic());
:+1: very clean

2022-11-18 13:54 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/DocumentIDStrategy.java
> +                               final BiFunction<DocWriteRequest<?>, SinkRecord, DocWriteRequest<?>> updateRequest) {
Super minor, since this is function, `updateRequest` -> `requestUpdater` would be easier to read

2022-11-18 17:15 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/OpensearchSinkConnectorConfig.java
> +        System.out.println("OpenSearch Sink Connector Configuration Options");
:+1:

2022-11-18 17:17 UTC, reta commented on docs/opensearch-sink-connector-config-options.rst
> +  List of Opensearch HTTP connection URLs e.g. ``http://eshost1:9200,http://eshost2:9200``.
@deepdatta LGTM, please revert the `Opensearch` leftovers

2022-11-18 21:16 UTC, reta commented on docs/opensearch-sink-connector-config-options.rst
> +Authentication
:+1:

2022-11-18 21:17 UTC, reta commented on src/main/java/io/aiven/kafka/connect/opensearch/OpensearchSinkConnectorConfig.java
> +            "List of OpenSearch HTTP connection URLs e.g. ``http://eshost1:9200,"
:+1: ty

2022-11-18 21:17 UTC, reta approved these changes

2022-11-18 21:17 UTC, reta commented
@C0urante LGTM?

2022-11-18 21:18 UTC, reta requested changes
@deepdatta tests / checks on CI are failing

2022-11-18 21:32 UTC, deepdatta commented
Fixed checkstyle errors

2022-11-18 21:38 UTC, reta submitted a review, later dismissed

2022-11-24 13:34 UTC, willyborankin requested changes
@deepdatta Perfect work. Could you please extend integration tests here:
https://github.com/aiven/opensearch-connector-for-apache-kafka/blob/main/src/integration-test/java/io/aiven/kafka/connect/opensearch/OpensearchSinkConnectorIT.java
And I will merge it.

2022-11-28 16:55 UTC, deepdatta commented
Added Integration test for key.igonore.id.strategy config

2022-11-29 10:05 UTC, willyborankin approved these changes

2022-11-29 10:05 UTC, merged