Simplify code: Fix typos, refactor logic, and remove unused parameters.
aiven/opensearch-connector-for-apache-kafka pull request #329
Opened 2024-12-13 13:59 UTC by madplay

This PR improves code quality by:
- Fixing typos, optimizing iteration.
- Refactoring logic, removing unused parameters.

I found this project while looking into Kafka connectors. It's really impressive, thanks ☺️

2025-07-29 13:18 UTC, Claudenw requested changes

2025-07-29 13:18 UTC, Claudenw commented on src/main/java/io/aiven/kafka/connect/opensearch/RetryUtil.java
> +                    LOGGER.warn(msg + "Failure reason: ", e);
This should probably be:
```
LOGGER.warn("{} Failure reason {}", msg, e.getMessage(), e);
```
or something similar.  Perhaps just
```
LOGGER.warn(msg,  e);
```

2025-07-29 13:18 UTC, Claudenw commented on src/main/java/io/aiven/kafka/connect/opensearch/spi/ClientsConfiguratorProvider.java
> +        for (OpensearchClientConfigurator configurator : loaders) {
This could be replaced with 
```
return ServiceLoader
                .load(OpensearchClientConfigurator.class, ClientsConfiguratorProvider.class.getClassLoader()).stream().collect(Collectors.toList());
```

2026-05-02 15:44 UTC, closed without merging

2026-05-02 15:44 UTC, willyborankin commented
Pull request hasn’t had activity for a while